[package]
name = "scientific"
version = "0.1.3"
authors = ["ALeX Kazik <alex@kazik.de>"]
edition = "2021"
description = "Arbitrary precision scientific number (no_std capable, in pure Rust)"
repository = "https://github.com/alexkazik/scientific"
license = "MIT"
keywords = ["arbitrary", "precision", "scientific", "no_std"]
categories = ["mathematics", "science", "no-std"]

[dependencies]
serde = { version = "1.0", optional = true }

[dev-dependencies]
scientific-macro = "<0.5"

[features]
default = []
std = []
arc = []
debug = []

[package.metadata.docs.rs]
all-features = true
# enable unstable features in the documentation
rustdoc-args = ["--cfg", "docsrs"]
