name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 19 * * 3'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      # do a regular build and test
      - run: cargo build
      - run: cargo test

      # additional testing
      - run: cargo test --features=debug
      - run: cargo test --all-features

      # check fmt and clippy
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-features --tests -- -D warnings

      # ensure that the library doesn't use re-exports
      - run: RUSTFLAGS="--cfg no_re_export" cargo build -p scientific

      # check if the readme is up to date
      - run: cargo install cargo-rdme
      - run: cargo rdme --check
        working-directory: ./scientific
